### ISSUE TITLE
Install failing on Ubuntu 22.04/23.10 Desktop x86_64

### ISSUE THREAD

**Issue by CSerpent** [SpyGuard/SpyGuard#26]
Using newest git clone as of 2024-01-23.  Virgin Ubuntu 22.04 and 23.10.

Install completes, error as follows:

pi@spyguard:~/$ service spy* status
```
× spyguard-frontend.service - Spyguard frontend service
     Loaded: loaded (/lib/systemd/system/spyguard-frontend.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2024-01-23 09:59:17 GMT; 9min ago
   Main PID: 4797 (code=exited, status=1/FAILURE)
        CPU: 20ms

Jan 23 09:59:17 spyguard systemd[1]: Started Spyguard frontend service.
Jan 23 09:59:17 spyguard python3[4797]: Traceback (most recent call last):
Jan 23 09:59:17 spyguard python3[4797]:   File "/usr/share/spyguard/server/frontend/main.py", line 4, in <module>
Jan 23 09:59:17 spyguard python3[4797]:     from flask import Flask, render_template, send_from_directory, redirect, abort
Jan 23 09:59:17 spyguard python3[4797]: ModuleNotFoundError: No module named 'flask'
Jan 23 09:59:17 spyguard systemd[1]: spyguard-frontend.service: Main process exited, code=exited, status=1/FAILURE
Jan 23 09:59:17 spyguard systemd[1]: spyguard-frontend.service: Failed with result 'exit-code'.

× spyguard-watchers.service - spyguard watchers service
     Loaded: loaded (/lib/systemd/system/spyguard-watchers.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2024-01-23 10:00:40 GMT; 8min ago
   Main PID: 4814 (code=exited, status=1/FAILURE)
        CPU: 15ms

Jan 23 10:00:40 spyguard systemd[1]: Started spyguard watchers service.
Jan 23 10:00:40 spyguard python3[4814]: Traceback (most recent call last):
Jan 23 10:00:40 spyguard python3[4814]:   File "/usr/share/spyguard/server/backend/watchers.py", line 4, in <module>
Jan 23 10:00:40 spyguard python3[4814]:     from app.utils import get_watchers
Jan 23 10:00:40 spyguard python3[4814]:   File "/usr/share/spyguard/server/backend/app/__init__.py", line 4, in <module>
Jan 23 10:00:40 spyguard python3[4814]:     from sqlalchemy import create_engine, MetaData, Table
Jan 23 10:00:40 spyguard python3[4814]: ModuleNotFoundError: No module named 'sqlalchemy'
Jan 23 10:00:40 spyguard systemd[1]: spyguard-watchers.service: Main process exited, code=exited, status=1/FAILURE
Jan 23 10:00:40 spyguard systemd[1]: spyguard-watchers.service: Failed with result 'exit-code'.

× spyguard-backend.service - Spyguard backend service
     Loaded: loaded (/lib/systemd/system/spyguard-backend.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2024-01-23 09:59:17 GMT; 9min ago
   Main PID: 4800 (code=exited, status=1/FAILURE)
        CPU: 18ms

Jan 23 09:59:17 spyguard systemd[1]: Started Spyguard backend service.
Jan 23 09:59:17 spyguard python3[4800]: Traceback (most recent call last):
Jan 23 09:59:17 spyguard python3[4800]:   File "/usr/share/spyguard/server/backend/main.py", line 4, in <module>
Jan 23 09:59:17 spyguard python3[4800]:     from flask import Flask, render_template, send_from_directory, jsonify, redirect
Jan 23 09:59:17 spyguard python3[4800]: ModuleNotFoundError: No module named 'flask'
Jan 23 09:59:17 spyguard systemd[1]: spyguard-backend.service: Main process exited, code=exited, status=1/FAILURE
Jan 23 09:59:17 spyguard systemd[1]: spyguard-backend.service: Failed with result 'exit-code'.
```

**Comment by b068931cc450442b63f5b3d276ea4297** [comment]
Hi, thank you for this issue.

I have just tried it with `ubuntu-22.04.3-desktop-amd64` with a fresh install.

`sudo apt install python3-venv` is missing.

In my test it worked after running uninstall.sh and then reinstalling SpyGuard.

I will add it to the code in the coming days after a few tests.

**Comment by b068931cc450442b63f5b3d276ea4297** [comment]
should work with the new install.sh #28

**Comment by CSerpent** [comment]
Confirmed working, Ubuntu 23.10.
