### ISSUE TITLE
Report not being generated when SSID prefix name contain a number

### ISSUE THREAD

**Issue by ldina** [SpyGuard/SpyGuard#47]
I had a nice couple of hours investigating why suddenly the report was not generated.

The error in the frontend was:
```
Traceback (most recent call last):
  File "/usr/share/spyguard/analysis/analysis.py", line 74, in <module>
    analyze(sys.argv[1])
  File "/usr/share/spyguard/analysis/analysis.py", line 62, in analyze
    report = Report(capture_folder, analysis_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/spyguard/analysis/classes/report.py", line 22, in __init__
    self.capinfos = self.read_json(os.path.join(capture_directory, "assets/capinfos.json"))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/spyguard/analysis/classes/report.py", line 46, in read_json
    with open(json_path, "r") as json_file:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/0AEBB786/assets/capinfos.json'

```
So the report expected to read capinfos.json but did not find it.

So I went where the capinfo file is generated 
https://github.com/SpyGuard/SpyGuard/blob/master/server/frontend/app/classes/capture.py
and here
 ```
def stop_capture(self) -> dict:
        """Stop dumpcap & suricata if any instance present & ask create_capinfos.

        Returns:
            dict: operation status
        """
        network = Network()

        # We stop the monitoring and the associated hotspot. 
        if stop_monitoring(): 
            if network.delete_hotspot():
                self.create_capinfos()
                return {"status": True,
                        "message": "Capture stopped"}
            else:
                return {"status": False,
                        "message": "No active hotspot"}     
        else:
            return {"status": False,
                    "message": "No active capture"}

```
 I discovered that the file is generated only when the network.delete_hotspot is invocated
so I went here
https://github.com/SpyGuard/SpyGuard/blob/master/server/frontend/app/classes/network.py
and i discovered that 
 ```
def delete_hotspot(self) -> bool:
        """
            Delete the previously created hotspot. 
        """
        sh = sp.Popen(["nmcli", "con", "show"], stdout=sp.PIPE, stderr=sp.PIPE)
        for line in sh.communicate()[0].splitlines():
            line = line.decode('utf8')
            if self.iface_in in line:
                ssids = re.search("^[a-zA-Z]+\-[0-9a-f]{4}", line)
                if ssids:
                    sp.Popen(["nmcli", "con", "delete", ])
                    sh = sp.Popen(["nmcli", "con", "delete", ssids[0]], stdout=sp.PIPE, stderr=sp.PIPE)
                    sh = sh.communicate()

                    if re.match(".*[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}.*", sh[0].decode("utf8")):
                        return True
                    else:
                        return False
```
expect to delete a hotspot name where the first part of the SSID name contains only letters.

Because I had customized the SSID name with a number, the delete_hotspot was not working, the capinfos not generated, the report errored.

**So please adjust the regex in ssid to manage also numbers or prevent the user in the backend configuration  from adding unsupported SSID prefixes.**

**Comment by Bayernuard** [comment]
Did you ever have any progress fixing this issue? I haven't customized my SSID name, but report is still failing to generate (see #58).
